import Head from "next/head";
import styles from "../styles/Home.module.css";

const About = () => {
	return (
		<div>
			<Head>
				<title>About us</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>Welcome to Buff Market</h1>
				<p className={styles.description}>A Buff.market Clone by M Waleed</p>
			</main>
		</div>
	);
};

export default About;
